### ISSUE TITLE
长时间进行识别二维码,一直未成功,然后溢出了

### ISSUE THREAD

**Issue by bilifo** [kangdp/StarBarcode#1]
03-16 11:32:49.726 3984-4240/com.dense.kuiniu.dense_frame E/AndroidRuntime: FATAL EXCEPTION: DecodeBarCodeThread
    Process: com.dense.kuiniu.dense_frame, PID: 3984
    java.lang.ArrayIndexOutOfBoundsException: length=60; index=84
        at com.google.zxing.common.BitArray.get(BitArray.java:68)
        at com.google.zxing.oned.rss.RSS14Reader.parseFoundFinderPattern(RSS14Reader.java:328)
        at com.google.zxing.oned.rss.RSS14Reader.decodePair(RSS14Reader.java:161)
        at com.google.zxing.oned.rss.RSS14Reader.decodeRow(RSS14Reader.java:69)
        at com.google.zxing.oned.MultiFormatOneDReader.decodeRow(MultiFormatOneDReader.java:96)
        at com.google.zxing.oned.OneDReader.doDecode(OneDReader.java:155)
        at com.google.zxing.oned.OneDReader.decode(OneDReader.java:54)
        at com.google.zxing.MultiFormatReader.decodeInternal(MultiFormatReader.java:171)
        at com.google.zxing.MultiFormatReader.decodeWithState(MultiFormatReader.java:85)
        at com.kdp.starbarcode.core.BarCodeReaderManager.decodeWithState(BarCodeReaderManager.java:39)
        at com.kdp.starbarcode.core.BarCodeProcessor.decodeFrame(BarCodeProcessor.java:163)
        at com.kdp.starbarcode.core.BarCodeProcessor.access$100(BarCodeProcessor.java:27)
        at com.kdp.starbarcode.core.BarCodeProcessor$DecodeCallback.handleMessage(BarCodeProcessor.java:128)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:135)
        at android.os.HandlerThread.run(HandlerThread.java:61)

**Comment by kangdp** [comment]
好的，我知道了

**Comment by kangdp** [comment]
想问一下，长时间大概多久会出现这个问题？

**Comment by bilifo** [comment]
嗯,是我打断点,在debuger时,出现的,但debug并没进入,一直是在回调未识别成功.偶现,概率不是很高,后面复测过3次,一样的条件下,没出现当然也是回调未识别

**Comment by kangdongpu** [comment]
> 嗯,是我打断点,在debuger时,出现的,但debug并没进入,一直是在回调未识别成功.偶现,概率不是很高,后面复测过3次,一样的条件下,没出现当然也是回调未识别

**Comment by kangdp** [comment]
你的那个二维码发一下，我这边试试

**Comment by bilifo** [comment]
我就是拿自己的微信二维码测的,这个需要吗?

**Comment by kangdp** [comment]
好的，我看下
